language: ruby
script: bundle exec cucumber
rvm:
- ruby-head
- jruby-head
- jruby-19mode
- 2.2
- 2.1
- 2.0
- 1.9.3
os:
- linux
- osx
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-19mode
  - rvm: jruby-head
env: TEST=true
notifications:
  slack:
    secure: rNtdHH64xqS8pFVGbmtPbbV9T0oDheX5/4s1BnHY0W57WgixJIJhq/lnp6opQWmuPqgdYIEmUIxkBppHoIUJBVIc4ZRi7bC1bVm59Fc2LkJ+GFy372FpalhFVW6zRwAxAXnkrU5fzCVWGzEiyZ875jGDeyCxSAs5JdLshu6+hGA=
