language: ruby
sudo: false
cache: bundler
rvm:
- ruby-head
- jruby-head
- 2.2
- 2.1
- 2.0
os:
- linux
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
script: bundle exec cucumber
env: TEST=true
notifications:
  slack:
    secure: rNtdHH64xqS8pFVGbmtPbbV9T0oDheX5/4s1BnHY0W57WgixJIJhq/lnp6opQWmuPqgdYIEmUIxkBppHoIUJBVIc4ZRi7bC1bVm59Fc2LkJ+GFy372FpalhFVW6zRwAxAXnkrU5fzCVWGzEiyZ875jGDeyCxSAs5JdLshu6+hGA=
